<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<PublishReadyToRun>true</PublishReadyToRun>
	<PublishSingleFile>true</PublishSingleFile>
	<PublishTrimmed>true</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
	
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>embedded</DebugType>
	<DeterministicSourcePaths>True</DeterministicSourcePaths>
  </PropertyGroup>

</Project>
