name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
       sudo apt update && sudo apt install gnupg2 libc6-dev -y
       sudo apt-get install apt-transport-https
       sudo echo "deb https://notesalexp.org/debian/buster/ buster main" >> /etc/apt/sources.list
       wget -O - https://notesalexp.org/debian/alexp_key.asc | sudo apt-key add -
       sudo apt-get update
       apt update && apt install tesseract-ocr=4.1.1+git4247-97079fa3-1 -y
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ./WFInfo.Services.Tests/WFInfo.Services.Tests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
